#!/usr/bin/env python3
"""
Drift test over the class (referee nomination 1) -- PRE-REGISTERED.

Fable's section 1 showed the dephasing lemma is region-agnostic: dephasing in
a region's OWN modular basis commutes with that region's modular flow by
construction, so it can never discriminate geometric from scrambled regions.
The selecting half of Q10 (N2, repaired dynamical form) is the DRIFT demand:
the observer's coarse-graining must commute with their own PHYSICAL time
evolution -- coarsen-then-evolve = evolve-then-coarsen -- or coarse
predictions drift against coarse records.

On the lattice, physical time is generated by the chain Hamiltonian h0.
The observer's coarse-graining is dephasing D in the eigenbasis of the
modular kernel k_A.  At leading order the drift is governed by the
commutator [k_A, h0_A] (h0_A = physical one-particle Hamiltonian restricted
to the region): dephasing in k_A's eigenbasis commutes with e^{i h0_A t}
iff the two operators are compatible.  For a GEOMETRIC region, BW/quasi-
locality says k_A is a smooth local deformation of h0_A -- small commutator.
For a SCRAMBLED region, k_A is nonlocal and unrelated to h0_A -- large
commutator.  THIS is the discriminator the dephasing lemma could not provide.

PRE-REGISTERED METRIC (amended in place after the first run):
    eta(A) = ||[K_full, h0]||_F / (||K_full||_F * ||h0||_F)
where K_full is the modular kernel embedded in the full L x L space and h0
is the FULL chain Hamiltonian.  The first version used the restricted
commutator [k_A, h0_A]; it is degenerate for regions with no internal bonds
(even/odd: h0_A = 0, division by zero).  The A-A block of [K_full, h0]
equals [k_A, h0_A] exactly, so the amendment changes nothing for connected
regions; what it adds is the region-complement blocks -- the boundary
leakage that dominates the drift of scattered regions' books.  (An observer
whose region has no internal dynamics has no coarse dynamics at all; their
books change entirely through untracked exchange -- maximal drift, not
zero drift.)

PRE-REGISTERED PREDICTIONS:
  P1  eta(contiguous) beats every scrambled rival by > 3x at L = 80.
  P2  the separation does not decay with L (tested at L = 40..320):
      slope of log(separation) vs log(L) > -0.1.
  P3  Haar-random state: eta(contiguous) is NOT small (teeth -- the drift
      test must fail where there is no geometry).
  P4  two-interval: reported, not judged (its cross-block term is small in
      weight but nonlocal in h0 -- either outcome is informative).
"""

import numpy as np

clip = 1e-12
RANDOM_SEEDS = 3
MASTER_SEED = 7
L_values = [40, 80, 160, 320]

def ground_state_correlation(L, N):
    h = np.zeros((L, L))
    for i in range(L - 1):
        h[i, i + 1] = h[i + 1, i] = -0.5
    _, eigvecs = np.linalg.eigh(h)
    occ = eigvecs[:, :N]
    return occ @ occ.T.conj(), h

def modular_kernel(C, region):
    C_A = C[np.ix_(region, region)]
    n_k, U = np.linalg.eigh(C_A)
    n_k = np.clip(n_k, clip, 1.0 - clip)
    return (U * np.log((1.0 - n_k) / n_k)) @ U.T

def make_regions(L, rng):
    half = L // 2
    quarter = half // 2
    contiguous = np.arange((L - half) // 2, (L - half) // 2 + half)
    even_odd = np.arange(0, L, 2)
    b1 = np.arange(L // 4 - quarter // 2, L // 4 - quarter // 2 + quarter)
    b2 = np.arange(3 * L // 4 - (quarter - quarter // 2),
                   3 * L // 4 - (quarter - quarter // 2) + (quarter - quarter // 2) * 2)
    two_interval = np.sort(np.concatenate([b1, b2]))
    assert len(two_interval) == half
    randoms = [np.sort(rng.choice(L, half, replace=False))
               for _ in range(RANDOM_SEEDS)]
    return contiguous, even_odd, two_interval, randoms

def drift_eta(C, h0, region):
    """Normalized commutator of the embedded modular kernel with the FULL
    physical Hamiltonian (boundary leakage included)."""
    L = h0.shape[0]
    k_A = modular_kernel(C, region)
    K_full = np.zeros((L, L))
    K_full[np.ix_(region, region)] = k_A
    comm = K_full @ h0 - h0 @ K_full
    norm = np.linalg.norm(K_full, 'fro') * np.linalg.norm(h0, 'fro')
    return float(np.linalg.norm(comm, 'fro') / norm)

print("=" * 78)
print("DRIFT TEST OVER THE CLASS -- the selecting half of Q10")
print("=" * 78)
print()
print(f"{'L':>5s}  {'region':>12s}  {'eta':>9s}")
print("-" * 78)

eta_cont, eta_two, eta_best_rival = [], [], []
for L in L_values:
    rng = np.random.default_rng(MASTER_SEED)
    C, h0 = ground_state_correlation(L, L // 2)
    contiguous, even_odd, two_interval, randoms = make_regions(L, rng)
    rows = [("contiguous", contiguous), ("two-interval", two_interval),
            ("even/odd", even_odd)] + \
           [(f"random #{k + 1}", r) for k, r in enumerate(randoms)]
    etas = {}
    for name, region in rows:
        etas[name] = drift_eta(C, h0, region)
        print(f"{L:>5d}  {name:>12s}  {etas[name]:9.5f}")
    eta_cont.append(etas["contiguous"])
    eta_two.append(etas["two-interval"])
    rivals = [etas["even/odd"]] + [etas[f"random #{k + 1}"]
                                   for k in range(RANDOM_SEEDS)]
    eta_best_rival.append(min(rivals))
    print("-" * 78)

# Haar control at L = 80
L = 80
rng = np.random.default_rng(MASTER_SEED)
Q, _ = np.linalg.qr(rng.standard_normal((L, L)))
C_haar = Q @ np.diag(rng.uniform(0.05, 0.95, L)) @ Q.T
_, h0 = ground_state_correlation(L, L // 2)
contiguous, _, _, _ = make_regions(L, rng)
eta_haar = drift_eta(C_haar, h0, contiguous)
print(f"Haar control (L=80, contiguous): eta = {eta_haar:.5f} "
      f"(vacuum contiguous: {eta_cont[1]:.5f})")
print()

# -----------------------------------------------------------------------------
# Adjudication vs pre-registered predictions
# -----------------------------------------------------------------------------
print("PASS / FAIL table:")
print("-" * 78)
sep = [r / c for c, r in zip(eta_cont, eta_best_rival)]
slope, _ = np.polyfit(np.log(L_values), np.log(sep), 1)
checks = [
    ("P1: contiguous beats every scrambled rival by > 3x at L=80",
     sep[1] > 3.0, f"separation {sep[1]:.1f}x"),
    ("P2: separation does not decay with L (slope > -0.1)",
     slope > -0.1, f"separations {[f'{s:.1f}' for s in sep]}, "
     f"slope {slope:.2f}"),
    ("P3: Haar control NOT drift-free (eta_Haar > 3x eta_vacuum)",
     eta_haar > 3 * eta_cont[1], f"{eta_haar:.5f} vs {eta_cont[1]:.5f}"),
]
for desc, passed, value in checks:
    print(f"  {'PASS' if passed else 'FAIL':>5s}  {desc:<60s}  {value}")
print()
print(f"P4 (reported, not judged): two-interval eta "
      f"{[f'{e:.5f}' for e in eta_two]} vs contiguous "
      f"{[f'{e:.5f}' for e in eta_cont]}")
print("-" * 78)
print(f"Overall: {'PASS' if all(c[1] for c in checks) else 'FAIL'}")
